# core/dotfiles
brew "bats-core"
brew "stow"
brew "grep"

# browsing
brew "firefox"

# user interface
brew "tmux"

# file navigation and viewing
brew "tree"
brew "bat"

# developer tools
brew "activemq"
brew "jq"
brew "maven"
brew "node"

# fun
brew "sl"